### ISSUE TITLE
docs: Missing link to the source of the backend server

### ISSUE THREAD

**Issue by ajhsu** [billcccheng/js-popular-variable-frontend#1]
The link to [the source of the backend server](https://github.com/billcccheng/js-popular-variable-server) seems not set correctly in the README file. (Or it was renamed, maybe?)

**Comment by billcccheng** [comment]
Sorry @ajhsu! I updated the documentation! If you have any more questions, please let me know!

**Comment by ajhsu** [comment]
Now it's fixed.
And I really love the idea by the way 👍
